### ISSUE TITLE
please, share, which tools did you used for such beautiful diagrams creation

### ISSUE THREAD

**Issue by iharh** [hds/hegdenu.net#2]
Hello.
Please, share, which tools did you used for such beautiful diagrams creation

**Comment by hds** [comment]
@iharh For the "understanding async/await" series, all the diagrams were created with D2. You can learn more about D2 and download it from https://d2lang.com/. It takes text based input and produces an image. I used SVGs for the blog posts.

All the diagrams are already in this repo: https://github.com/hds/hegdenu.net/tree/main/resources/understanding-async-await/diagrams

There is a shell script which compiles the diagram source to SVG is here: https://github.com/hds/hegdenu.net/blob/main/resources/understanding-async-await/diagrams/build_diagrams.sh

I used the `"200"` theme, which is a "dark mode" theme in D2.

**Comment by iharh** [comment]
Thank you very much!!! Will try D2.
